### PR TITLE
User can drop private egg

### PR DESCRIPTION
**Pull request by mpowers1113**

### CODE REVIEW

**Comment by mpowers1113** [comment]
glenUserGif

**Comment by mpowers1113** [comment]
jobUserGif

**Comment by mpowers1113** [comment]
mattUserGif

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Try to combine your back end and front end code for public and private eggs. If you get stuck, please let me know.

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please try to refactor your API route to not need a big if else

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
